server:
  port: 9999
spring:
  datasource:
    dynamic:
      datasource:
        e1:
          url: jdbc:mysql://localhost:3306/all1
          username: root
          password: 123123123
          driverClassName: com.mysql.cj.jdbc.Driver
        e2:
          url: jdbc:mysql://localhost:3306/all2
          username: root
          password: 123123123
          driverClassName: com.mysql.cj.jdbc.Driver
      primary: e1